### ISSUE TITLE
Same issue here

### ISSUE THREAD

**Issue by shahidshakeel** [bmjohns/SizingClassTest#1]
Hey @bmjohns, same issue for me. Did you find any solution? Don't understand why people downvoted your question on StackOverflow 🤷‍♂️

**Comment by bmjohns** [comment]
Hello @shahidshakeel, I'd like to know as well haha, no comments really why it was downvoted. I do have some findings since my last post (but no responses on StackOverflow or Apple Feedback where I also posted this).

1. My project at work had an issue where I was setting the sizing class programmatically to get around the Xcode 16 tab bar updates (where it now appears different when in iPad, or size class (wR, hR). Removing that resolved most of the issues. `   traitOverrides.horizontalSizeClass = .compact`
2. In the sample project the constraints that depend on size class will also depend on how you are presenting the ViewController. If you present automatically or in a not full page way (ie full screen) then the size class (wR, hR) will not be applied. I believe there is still a bug in Xcode 16 where the GUI of storyboard will not show this distinction, but only during runtime on sim or device. If you take my sample project and change the presentation style of the second VC with the label to `full screen` it will properly apply the (wR, hR) on build

<img width="261" alt="Screenshot 2024-12-02 at 10 29 25 AM" src="https://github.com/user-attachments/assets/15e2a0ab-66d3-4233-981d-b3ebc1e3d104">
